name: Deploy Coscine Static Site to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ vars.COSCINE_SUBPROJECT_NAME }}
      COSCINE_API_TOKEN: ${{ secrets.COSCINE_API_TOKEN }} 
    steps:
      - name: Check Python version
        run: python -V

      - name: Install git
        run: sudo apt install -y git

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy webpage
        run: |
          pwd
          mkdir -p public/
          dir
          cp index.html public/
          cp style.css public/
          cp coscine_logo.gif public/

      - name: Clone repository
        run: git clone https://git.rwth-aachen.de/coscine/community-features/coscine-static-site-generator.git

      - name: Install requirements
        working-directory: ./coscine-static-site-generator/
        run: pip install -r requirements.txt
    
      - name: Build static site and generate navigation tabs
        working-directory: ./coscine-static-site-generator/
        run: |
          RESOURCE_NAMES=("Liver Imaging V8 S3")
      
          for RESOURCE in "${RESOURCE_NAMES[@]}"; do
            # turn spaces into underscores:
            SLUG=${RESOURCE// /_}
            echo "Processing resource: $RESOURCE → $SLUG"
            mkdir -p ../public/"$SLUG"
            python -m src -t "$COSCINE_API_TOKEN" -p "$PROJECT_NAME" -r "$RESOURCE" -y -o ../public/"$SLUG" --subproject
          done
      
      - name: Debug build output
        run: |
          echo "🔍 Contents of public/:"
          find public -maxdepth 3 | sed 's/^/   /'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
